version: "3.9"
services:
  nginx_server:
    image: nginx
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb       # Menentukan database default
      MYSQL_USER: user           # Menentukan username untuk user baru
      MYSQL_PASSWORD: userpass   # Menentukan password untuk user baru
    volumes:
     - my-docker-setup_mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  my-docker-setup_mysql_data:
    driver: local

